name: base
channels:
  - conda-forge
  - intel
  - ccpi
  - astra-toolbox
  - defaults
dependencies:
  - cil
  - tomophantom=2.0.0
  - astra-toolbox
  - tigre=2.2
  - ccpi-regulariser=21.0.0
  - xraylib # IBSim training
  - k3d # IBSim training
  - psutil
  - pip
  - pip:
    - cma
    - gvxr # IBSim training
    - xpecgen # IBSim training
    - simpleitk
    - git+https://bitbucket.org/spekpy/spekpy_release.git
  
