name: ImageBuilderToHarbor
on: [workflow_dispatch] # Can be changed, however for testing purposes it is set to workflow dispatch
jobs:
  findDockerFile:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.python.outputs.myOutput}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Find file
        id: python
        uses: vovsike/FirstAction@main
  buildDockerFile:
    needs: findDockerFile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.findDockerFile.outputs.matrix) }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        continue-on-error: true
        with:
          context: ${{matrix.ImageName}}
          tags: harbor.stfc.ac.uk/image-builder-testing/${{matrix.ImageName}}:latest
          push: false